name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # تأكد من تحديث رقم النسخة حسب متطلبات المشروع

      - name: Cache Flutter Pub Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Run Code Analyzer (Lint)
        run: flutter analyze

      - name: Check Code Formatting
        run: flutter format --set-exit-if-changed .

      - name: Run Unit Tests (Services)
        run: flutter test test/services

      - name: Run UI Tests (Screens)
        run: flutter test test/screens

  deploy:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token $FIREBASE_TOKEN
