name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        run: flutter analyze

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Deploy to Firebase
        run: flutter build web && firebase deploy --only hosting
