name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  setup:
    name: Set up Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 'stable'

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests for services
        run: flutter test test/services

      - name: Run UI tests for screens
        run: flutter test test/screens

  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        run: flutter analyze

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Web
        run: flutter build web --release

      - name: Deploy to Firebase
        run: |
          echo "Branch: ${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            firebase deploy --only hosting --project=production
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            firebase deploy --only hosting --project=staging
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/
          if-no-files-found: error
