name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests for services
        run: flutter test test/services

      - name: Run UI tests for screens
        run: flutter test test/screens

  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        run: flutter analyze

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Deploy to Firebase
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            flutter build web && firebase deploy --only hosting --project=production
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            flutter build web && firebase deploy --only hosting --project=staging
          fi
